name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # triggers on push to main branch

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Get AWS Account ID dynamically
      - name: Get AWS Account ID
        id: aws-account
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      # 4️⃣ Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 5️⃣ Build, tag, and push Docker image
      - name: Build, tag, and push image
        env:
          IMAGE_TAG: ${{ github.sha }}  # unique commit SHA
        run: |
          ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          IMAGE_NAME=${ECR_REGISTRY}/${ECR_REPOSITORY}

          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:latest .

          echo "Tagging with commit SHA..."
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${IMAGE_TAG}

          echo "Pushing both tags to ECR..."
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${IMAGE_TAG}

          echo "✅ Successfully pushed:"
          echo " - $IMAGE_NAME:latest"
          echo " - $IMAGE_NAME:${IMAGE_TAG}"
